#!/usr/bin/python3

import sys
import os
import subprocess

from http import server
from urllib import parse
import socketserver

PORT = 4200
INDEXFILE = 'index.html'


class MyHandler(server.SimpleHTTPRequestHandler):
    def do_GET(self):
        # Parse query data to find out what was requested
        parsedParams = parse.urlparse(self.path)

        # See if the file requested exists
        if os.access('.' + os.sep + parsedParams.path, os.R_OK):
            # File exists, serve it up
            if parsedParams.path == '/':
                subprocess.run("./build", shell=True)
            server.SimpleHTTPRequestHandler.do_GET(self)
        else:
            # send index.html, but don't redirect
            subprocess.run("./build", shell=True)
            self.send_response(200)
            self.send_header('Content-Type', 'text/html')
            self.end_headers()
            with open(INDEXFILE, 'rb') as fin:
                self.copyfile(fin, self.wfile)


if __name__ == "__main__":

    args = sys.argv[1:]

    if len(args) > 0:
        PORT = int(args[0])

    httpd = socketserver.TCPServer(("", PORT), MyHandler)

    sys.stdout.write("Serving at port: %s\n" % PORT)
    httpd.serve_forever()